name: lmdownload
version: latest
version-script: cat version
summary: Linux Magazine PDF downloader for subscribers
grade: stable
confinement: strict
description: |
  Linux Magazine PDF downloader for subscribers
  https://github.com/pbek/lmdownload

apps:
  lmdownload:
    command: lmdownload
    # see https://docs.snapcraft.io/reference/interfaces
    plugs: [home, network, removable-media]

parts:
#  go:
#  lmdownload:
#    # see https://snapcraft.io/docs/go-plugin
#    plugin: go
#    source: .
#    go-importpath: github.com/pbek/lmdownload
#    build: |
#      #export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
#      #export PATH=$GOPATH/bin:$PATH
#      ./build.sh
#      ./bin/lmdownload -v
#    install: |
#      cp -a ./bin/lmdownload $SNAPCRAFT_PART_INSTALL
#    after: [go]

  lmdownload:
    plugin: nil
    source: .
    build-snaps: [go]
    override-build: |
      export VERSION_NUMBER=`cat version`
      go build -ldflags "-X main.version=$VERSION_NUMBER" -o $SNAPCRAFT_PART_INSTALL/bin/lmdownload -i .
      find $SNAPCRAFT_PART_INSTALL
      echo "Done building"
