name: lmdownload
version: "VERSION-STRING"
summary: Linux Magazine PDF downloader for subscribers
grade: stable
confinement: strict
description: |
  Linux Magazine PDF downloader for subscribers
  https://github.com/pbek/lmdownload

apps:
  lmdownload:
    command: bin/lmdownload
    # see https://docs.snapcraft.io/reference/interfaces
    plugs: [home, network, removable-media]

parts:
  lmdownload:
    source: .
    # see https://docs.snapcraft.io/reference/plugins/go
    plugin: go
    go-importpath: github.com/pbek/lmdownload
    build-packages:
      - git
    build: |
      #export GOPATH=$(dirname $SNAPCRAFT_PART_INSTALL)/go
      #export PATH=$GOPATH/bin:$PATH
      ./build.sh
      ./lmdownload -v
    install: |
      cp -a lmdownload $SNAPCRAFT_PART_INSTALL/bin/lmdownload
    after: [go]
  go:
    source-tag: go1.10.1
